apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globetrotter

resources:
  - namespace.yaml
  - configmap.yaml
  - auth-db.yaml
  - itineraries-db.yaml
  - auth.yaml
  - destinations.yaml
  - recommendations.yaml
  - itineraries.yaml
  - gateway.yaml
  - ingress.yaml
