"""
Curated list of the world's most popular tourist destinations.

Includes a strong focus on African destinations and major tourist sites in Cameroon.
"""

TOP_TOURIST_DESTINATIONS = [
    # Europe
    {"name": "Rome", "country": "Italy", "continent": "Europe",
     "description": "The Eternal City – Colosseum, Vatican, ancient ruins and incredible Italian food.",
     "tags": ["history", "culture", "food", "romance"], "avg_cost_per_day": 100,
     "image": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop"},
    {"name": "London", "country": "United Kingdom", "continent": "Europe",
     "description": "Iconic landmarks, world-class museums, royal history and vibrant neighbourhoods.",
     "tags": ["city", "culture", "history", "shopping"], "avg_cost_per_day": 150,
     "image": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop"},
    {"name": "Amsterdam", "country": "Netherlands", "continent": "Europe",
     "description": "Canals, bikes, museums and a uniquely relaxed European vibe.",
     "tags": ["culture", "city", "history", "nature"], "avg_cost_per_day": 130,
     "image": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&h=600&fit=crop"},
    {"name": "Prague", "country": "Czechia", "continent": "Europe",
     "description": "Fairytale architecture, historic old town and affordable Central European charm.",
     "tags": ["history", "culture", "romance", "budget"], "avg_cost_per_day": 70,
     "image": "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&h=600&fit=crop"},
    {"name": "Istanbul", "country": "Turkey", "continent": "Europe",
     "description": "Where East meets West – bazaars, mosques, Bosphorus views and rich cuisine.",
     "tags": ["culture", "history", "food", "city"], "avg_cost_per_day": 65,
     "image": "https://images.unsplash.com/photo-1524231757912-21f4fe64ae86?w=800&h=600&fit=crop"},
    {"name": "Lisbon", "country": "Portugal", "continent": "Europe",
     "description": "Sunny hills, tiled streets, pastel de nata and Atlantic coast vibes.",
     "tags": ["culture", "food", "beach", "budget"], "avg_cost_per_day": 75,
     "image": "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&h=600&fit=crop"},
    {"name": "Venice", "country": "Italy", "continent": "Europe",
     "description": "Romantic canals, gondolas and timeless Italian architecture.",
     "tags": ["romance", "culture", "history", "unique"], "avg_cost_per_day": 140,
     "image": "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&h=600&fit=crop"},
    {"name": "Florence", "country": "Italy", "continent": "Europe",
     "description": "Renaissance art capital – Uffizi, Duomo and Tuscan beauty.",
     "tags": ["culture", "history", "art", "food"], "avg_cost_per_day": 110,
     "image": "https://images.unsplash.com/photo-1543429258-0b43dbe83e0f?w=800&h=600&fit=crop"},
    {"name": "Vienna", "country": "Austria", "continent": "Europe",
     "description": "Imperial palaces, classical music and elegant café culture.",
     "tags": ["culture", "history", "food", "city"], "avg_cost_per_day": 115,
     "image": "https://images.unsplash.com/photo-1516550893923-42d28cc56732?w=800&h=600&fit=crop"},
    {"name": "Budapest", "country": "Hungary", "continent": "Europe",
     "description": "Thermal baths, ruin bars and stunning Danube views.",
     "tags": ["culture", "history", "budget", "unique"], "avg_cost_per_day": 60,
     "image": "https://images.unsplash.com/photo-1541343672885-9be56236302a?w=800&h=600&fit=crop"},

    # Asia
    {"name": "Seoul", "country": "South Korea", "continent": "Asia",
     "description": "K-culture capital – tech, street food, palaces and nightlife.",
     "tags": ["city", "food", "culture", "technology"], "avg_cost_per_day": 85,
     "image": "https://images.unsplash.com/photo-1517154421851-d9d5c2e2c0e8?w=800&h=600&fit=crop"},
    {"name": "Singapore", "country": "Singapore", "continent": "Asia",
     "description": "Futuristic city-state with amazing food, gardens and clean streets.",
     "tags": ["city", "food", "luxury", "culture"], "avg_cost_per_day": 130,
     "image": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600&fit=crop"},
    {"name": "Hong Kong", "country": "China", "continent": "Asia",
     "description": "Skyline views, street markets and a unique East-meets-West energy.",
     "tags": ["city", "food", "shopping", "culture"], "avg_cost_per_day": 120,
     "image": "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&h=600&fit=crop"},
    {"name": "Kyoto", "country": "Japan", "continent": "Asia",
     "description": "Temples, geishas, cherry blossoms and traditional Japanese beauty.",
     "tags": ["culture", "history", "nature", "romance"], "avg_cost_per_day": 100,
     "image": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&h=600&fit=crop"},
    {"name": "Phuket", "country": "Thailand", "continent": "Asia",
     "description": "Tropical beaches, clear waters and lively island nightlife.",
     "tags": ["beach", "nature", "food", "budget"], "avg_cost_per_day": 50,
     "image": "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&h=600&fit=crop"},
    {"name": "Maldives", "country": "Maldives", "continent": "Asia",
     "description": "Overwater villas, turquoise lagoons and ultimate tropical luxury.",
     "tags": ["beach", "luxury", "romance", "nature"], "avg_cost_per_day": 250,
     "image": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&h=600&fit=crop"},
    {"name": "Hanoi", "country": "Vietnam", "continent": "Asia",
     "description": "Old Quarter charm, street food heaven and rich history.",
     "tags": ["food", "culture", "budget", "history"], "avg_cost_per_day": 35,
     "image": "https://images.unsplash.com/photo-1559592413-7eaaaef917c5?w=800&h=600&fit=crop"},

    # Americas
    {"name": "Rio de Janeiro", "country": "Brazil", "continent": "South America",
     "description": "Christ the Redeemer, Copacabana beach and carnival energy.",
     "tags": ["beach", "nature", "culture", "adventure"], "avg_cost_per_day": 70,
     "image": "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop"},
    {"name": "Cancun", "country": "Mexico", "continent": "North America",
     "description": "Caribbean beaches, resorts and gateway to Mayan ruins.",
     "tags": ["beach", "luxury", "adventure", "food"], "avg_cost_per_day": 90,
     "image": "https://images.unsplash.com/photo-1510097467424-192d713c1c62?w=800&h=600&fit=crop"},
    {"name": "Los Angeles", "country": "USA", "continent": "North America",
     "description": "Hollywood, beaches, entertainment and endless sunshine.",
     "tags": ["city", "beach", "culture", "shopping"], "avg_cost_per_day": 160,
     "image": "https://images.unsplash.com/photo-1534190760961-74e8c1c5fd10?w=800&h=600&fit=crop"},
    {"name": "Las Vegas", "country": "USA", "continent": "North America",
     "description": "Entertainment capital – shows, casinos and desert spectacle.",
     "tags": ["city", "luxury", "unique", "shopping"], "avg_cost_per_day": 140,
     "image": "https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=800&h=600&fit=crop"},
    {"name": "Cusco", "country": "Peru", "continent": "South America",
     "description": "Gateway to Machu Picchu and heart of the Inca empire.",
     "tags": ["history", "adventure", "culture", "nature"], "avg_cost_per_day": 55,
     "image": "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&h=600&fit=crop"},
    {"name": "Buenos Aires", "country": "Argentina", "continent": "South America",
     "description": "Tango, steak, European-style avenues and late-night energy.",
     "tags": ["culture", "food", "city", "romance"], "avg_cost_per_day": 60,
     "image": "https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=800&h=600&fit=crop"},

    # ========== CAMEROON – Major tourist destinations ==========
    {"name": "Yaoundé", "country": "Cameroon", "continent": "Africa",
     "description": "Political capital of Cameroon – green hills, museums, monuments and lively markets.",
     "tags": ["city", "culture", "food", "history"], "avg_cost_per_day": 40,
     "image": "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&h=600&fit=crop"},
    {"name": "Douala", "country": "Cameroon", "continent": "Africa",
     "description": "Economic capital and largest city – busy port, nightlife, food and gateway to coastal trips.",
     "tags": ["city", "food", "culture", "shopping"], "avg_cost_per_day": 45,
     "image": "https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800&h=600&fit=crop"},
    {"name": "Mount Cameroon", "country": "Cameroon", "continent": "Africa",
     "description": "West Africa's highest peak – hike the active volcano, see lava fields and panoramic views.",
     "tags": ["adventure", "nature", "outdoor", "unique"], "avg_cost_per_day": 50,
     "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop"},
    {"name": "Limbe", "country": "Cameroon", "continent": "Africa",
     "description": "Black-sand beaches at the foot of Mount Cameroon – botanical garden, wildlife centre and seafood.",
     "tags": ["beach", "nature", "food", "adventure"], "avg_cost_per_day": 40,
     "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop"},
    {"name": "Kribi", "country": "Cameroon", "continent": "Africa",
     "description": "Cameroon's top beach destination – white sand, Lobé Waterfalls into the ocean, and fresh seafood.",
     "tags": ["beach", "nature", "food", "romance"], "avg_cost_per_day": 45,
     "image": "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&h=600&fit=crop"},
    {"name": "Lobé Waterfalls", "country": "Cameroon", "continent": "Africa",
     "description": "One of the few waterfalls in the world that empties directly into the ocean – near Kribi.",
     "tags": ["nature", "unique", "adventure", "photography"], "avg_cost_per_day": 40,
     "image": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&h=600&fit=crop"},
    {"name": "Bamenda", "country": "Cameroon", "continent": "Africa",
     "description": "Gateway to the North-West – highlands, traditional fondoms, waterfalls and cool climate.",
     "tags": ["culture", "nature", "history", "adventure"], "avg_cost_per_day": 35,
     "image": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop"},
    {"name": "Bafoussam", "country": "Cameroon", "continent": "Africa",
     "description": "Heart of the West Region – rich Bamileke culture, traditional chiefdoms and highland scenery.",
     "tags": ["culture", "history", "food", "unique"], "avg_cost_per_day": 35,
     "image": "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&h=600&fit=crop"},
    {"name": "Foumban", "country": "Cameroon", "continent": "Africa",
     "description": "Historic capital of the Bamoun Kingdom – palace museum, crafts and traditional architecture.",
     "tags": ["history", "culture", "unique", "shopping"], "avg_cost_per_day": 30,
     "image": "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&h=600&fit=crop"},
    {"name": "Rhumsiki", "country": "Cameroon", "continent": "Africa",
     "description": "Dramatic volcanic landscape in the Far North – needle-like peaks and traditional Kapsiki villages.",
     "tags": ["nature", "adventure", "unique", "photography"], "avg_cost_per_day": 35,
     "image": "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop"},
    {"name": "Waza National Park", "country": "Cameroon", "continent": "Africa",
     "description": "Far North safari park – elephants, giraffes, lions and classic Sahel wildlife viewing.",
     "tags": ["nature", "adventure", "wildlife", "outdoor"], "avg_cost_per_day": 55,
     "image": "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=600&fit=crop"},
    {"name": "Korup National Park", "country": "Cameroon", "continent": "Africa",
     "description": "One of Africa's oldest rainforests – incredible biodiversity, canopy walks and birdwatching.",
     "tags": ["nature", "adventure", "wildlife", "outdoor"], "avg_cost_per_day": 45,
     "image": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&h=600&fit=crop"},
    {"name": "Dja Faunal Reserve", "country": "Cameroon", "continent": "Africa",
     "description": "UNESCO World Heritage rainforest – gorillas, elephants and one of Africa's best-protected forests.",
     "tags": ["nature", "wildlife", "adventure", "unique"], "avg_cost_per_day": 50,
     "image": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop"},
    {"name": "Maroua", "country": "Cameroon", "continent": "Africa",
     "description": "Capital of the Far North – gateway to Waza, traditional markets and Sahel culture.",
     "tags": ["culture", "adventure", "history", "unique"], "avg_cost_per_day": 30,
     "image": "https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800&h=600&fit=crop"},
    {"name": "Garoua", "country": "Cameroon", "continent": "Africa",
     "description": "Northern city on the Benue River – markets, nearby national parks and Fulani culture.",
     "tags": ["culture", "nature", "adventure", "food"], "avg_cost_per_day": 30,
     "image": "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&h=600&fit=crop"},
    {"name": "Ngaoundéré", "country": "Cameroon", "continent": "Africa",
     "description": "Adamawa highland city – cool climate, cattle country and railway hub of the north.",
     "tags": ["culture", "nature", "adventure", "unique"], "avg_cost_per_day": 30,
     "image": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop"},
    {"name": "Buea", "country": "Cameroon", "continent": "Africa",
     "description": "University town on the slopes of Mount Cameroon – cool climate and base for volcano hikes.",
     "tags": ["adventure", "nature", "culture", "outdoor"], "avg_cost_per_day": 35,
     "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop"},
    {"name": "Ebolowa", "country": "Cameroon", "continent": "Africa",
     "description": "Gateway to southern rainforests and the Dja Reserve – cocoa country and forest culture.",
     "tags": ["nature", "culture", "adventure", "wildlife"], "avg_cost_per_day": 30,
     "image": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&h=600&fit=crop"},
    {"name": "Bertoua", "country": "Cameroon", "continent": "Africa",
     "description": "East Region capital – rainforest edge, logging towns and access to remote wildlife areas.",
     "tags": ["nature", "adventure", "wildlife", "unique"], "avg_cost_per_day": 30,
     "image": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop"},
    {"name": "Limbé Wildlife Centre", "country": "Cameroon", "continent": "Africa",
     "description": "Rescue centre for chimpanzees, gorillas and other primates – education and conservation tourism.",
     "tags": ["wildlife", "nature", "unique", "culture"], "avg_cost_per_day": 40,
     "image": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop"},

    # ========== More Africa ==========
    {"name": "Marrakech", "country": "Morocco", "continent": "Africa",
     "description": "Souks, riads, spices and the magic of the medina.",
     "tags": ["culture", "food", "adventure", "unique"], "avg_cost_per_day": 50,
     "image": "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&h=600&fit=crop"},
    {"name": "Cairo", "country": "Egypt", "continent": "Africa",
     "description": "Pyramids of Giza, Nile views and thousands of years of history.",
     "tags": ["history", "culture", "adventure", "unique"], "avg_cost_per_day": 45,
     "image": "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&h=600&fit=crop"},
    {"name": "Zanzibar", "country": "Tanzania", "continent": "Africa",
     "description": "Spice island beaches, Stone Town and Indian Ocean paradise.",
     "tags": ["beach", "culture", "nature", "romance"], "avg_cost_per_day": 70,
     "image": "https://images.unsplash.com/photo-1586861635166-cbfc8a8e0c0d?w=800&h=600&fit=crop"},
    {"name": "Cape Town", "country": "South Africa", "continent": "Africa",
     "description": "Table Mountain, beaches, wine lands and one of Africa's most beautiful cities.",
     "tags": ["nature", "beach", "adventure", "culture"], "avg_cost_per_day": 70,
     "image": "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&h=600&fit=crop"},
    {"name": "Serengeti", "country": "Tanzania", "continent": "Africa",
     "description": "World-famous safari plains – the Great Migration, lions and endless horizons.",
     "tags": ["wildlife", "nature", "adventure", "unique"], "avg_cost_per_day": 150,
     "image": "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=600&fit=crop"},
    {"name": "Victoria Falls", "country": "Zimbabwe", "continent": "Africa",
     "description": "One of the world's greatest waterfalls – mist, rainbows and adrenaline activities.",
     "tags": ["nature", "adventure", "unique", "photography"], "avg_cost_per_day": 80,
     "image": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&h=600&fit=crop"},
    {"name": "Lagos", "country": "Nigeria", "continent": "Africa",
     "description": "West Africa's megacity – beaches, Nollywood energy, food and nightlife.",
     "tags": ["city", "food", "culture", "beach"], "avg_cost_per_day": 55,
     "image": "https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800&h=600&fit=crop"},
    {"name": "Accra", "country": "Ghana", "continent": "Africa",
     "description": "Friendly capital – coastal forts, markets, music and a growing creative scene.",
     "tags": ["culture", "history", "food", "beach"], "avg_cost_per_day": 45,
     "image": "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&h=600&fit=crop"},
    {"name": "Nairobi", "country": "Kenya", "continent": "Africa",
     "description": "Safari gateway – national park in the city, museums and East African hub.",
     "tags": ["wildlife", "city", "adventure", "culture"], "avg_cost_per_day": 60,
     "image": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&h=600&fit=crop"},
    {"name": "Stone Town", "country": "Tanzania", "continent": "Africa",
     "description": "Historic heart of Zanzibar – alleys, spice markets and Swahili architecture.",
     "tags": ["history", "culture", "food", "unique"], "avg_cost_per_day": 65,
     "image": "https://images.unsplash.com/photo-1586861635166-cbfc8a8e0c0d?w=800&h=600&fit=crop"},
    {"name": "Luxor", "country": "Egypt", "continent": "Africa",
     "description": "Ancient Thebes – Valley of the Kings, temples and Nile cruises.",
     "tags": ["history", "culture", "unique", "adventure"], "avg_cost_per_day": 50,
     "image": "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&h=600&fit=crop"},
    {"name": "Dakar", "country": "Senegal", "continent": "Africa",
     "description": "Atlantic capital – Goree Island, music, markets and West African creativity.",
     "tags": ["culture", "history", "beach", "food"], "avg_cost_per_day": 50,
     "image": "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&h=600&fit=crop"},
    {"name": "Addis Ababa", "country": "Ethiopia", "continent": "Africa",
     "description": "Highland capital – coffee culture, museums and gateway to ancient sites.",
     "tags": ["culture", "history", "food", "unique"], "avg_cost_per_day": 40,
     "image": "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&h=600&fit=crop"},
    {"name": "Kigali", "country": "Rwanda", "continent": "Africa",
     "description": "Clean, green capital – genocide memorial, coffee and gateway to gorilla trekking.",
     "tags": ["culture", "nature", "wildlife", "adventure"], "avg_cost_per_day": 55,
     "image": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&h=600&fit=crop"},

    # Middle East
    {"name": "Petra", "country": "Jordan", "continent": "Asia",
     "description": "The Rose City – ancient rock-cut architecture and desert wonder.",
     "tags": ["history", "adventure", "unique", "culture"], "avg_cost_per_day": 80,
     "image": "https://images.unsplash.com/photo-1579606032821-4e6161c815ab?w=800&h=600&fit=crop"},

    # Oceania
    {"name": "Sydney", "country": "Australia", "continent": "Oceania",
     "description": "Opera House, Harbour Bridge, beaches and outdoor lifestyle.",
     "tags": ["city", "beach", "nature", "culture"], "avg_cost_per_day": 140,
     "image": "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop"},
    {"name": "Auckland", "country": "New Zealand", "continent": "Oceania",
     "description": "Harbour city with volcanoes, islands and adventure nearby.",
     "tags": ["nature", "adventure", "city", "outdoor"], "avg_cost_per_day": 110,
     "image": "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&h=600&fit=crop"},
]


def get_tourist_destinations() -> list:
    """Return top tourist destinations with sequential IDs starting at 2000."""
    results = []
    for i, dest in enumerate(TOP_TOURIST_DESTINATIONS, start=2000):
        entry = dict(dest)
        entry["id"] = i
        entry["source"] = "tourist_curated"
        results.append(entry)
    return results
